site_name: Condensed Matter Physics 
repo_url: https://pranabdas.github.io 
site_description: Notes on Condensed Matter Physics. 
site_author: Pranab Das 

nav:
  - Home: index.md 
  - Introduction: introduction.md 
  - Crystal structure: 
    - Single crystal: crystal-structure/single-crystal.md 
    - Bravais lattice: crystal-structure/lattice.md 
    - Reciprocal lattice and Brillouin zone: crystal-structure/reciprocal-lattice.md 
    - Miller indices and Bragg's diffraction: crystal-structure/bragg-diffraction.md 
  - Crystal growth: 
    - Various crystal growth methods: crystal-growth/crystal-growth.md 
    - Why single crystal: crystal-growth/why-single-crystal.md 
    - Flux method: crystal-growth/flux-method.md 
    - Bridgman method: crystal-growth/bridgman-method.md 
    - Czochralski method: crystal-growth/czochralski-method.md 
  - Characterization: 
    - Material characterization: characterization/characterization.md 
    - EDAX: characterization/edax.md 
    - Powder XRD: characterization/powder-xrd.md 
    - Laue Diffraction: characterization/laue.md 
  - ARPES: 
    - ARPES introduction: arpes/arpes-intro.md 
    - Three-step model: arpes/three-step-model.md 
    - ARPES setup: arpes/arpes-setup.md 
    - Spin-ARPES setup: arpes/spin-arpes.md 

theme: 
    name: null 
    custom_dir: simplicity 
    static_templates:
        - 404.html

    include_search_page: true
    search_index_only: false

    highlightjs: true
    hljs_languages: python

markdown_extensions:
  - pymdownx.arithmatex 
  - attr_list

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

copyright: © Copyright 2020 Pranab Das. All rights reserved. 

# google_analytics: [UA-163317742-1, https://pranabdas.github.io/]
